select * from customer
limit 20;

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as total_revenue from customer
group by gender;



--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount from customer
where discount_applied = 'Yes' 
and purchase_amount > (select avg(purchase_amount) from customer);



-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(AVG(review_rating)::numeric, 2) as average_review_rating from customer
group by 1
order by average_review_rating desc
limit 5;



--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, Round(avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by 1;



--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, count(customer_id) as total_customer, Round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_revenue
from customer
group by 1;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, 100.0*sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*) 
as products_percentage from customer
group by 1
order by products_percentage desc
limit 5;




--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

select 
	case 
		when previous_purchases <= 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal' end as customer_segment,
		count(*) from customer
		group by 1;
		




--Q8. What are the top 3 most purchased products within each category? 

with item as(
select item_purchased,category,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as rn
from customer
group by 1,2
)
select category,item_purchased,total_orders from item 
where rn<=3;




--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(*) as repeat_buyers from customer
where previous_purchases > 5
group by 1;





--Q10. What is the revenue contribution of each age group? 

select age_group, sum(purchase_amount) as total_revenue from customer
group by 1
order by 2 desc;